collections:
  - name: "blog-posts"
    label: "Articles de Blog"
    folder: "content/blog"
    format: "markdown"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Résumé", name: "summary", widget: "string" }
      - { label: "Corps du texte", name: "body", widget: "markdown" }
  - name: "static-pages"
    label: "Pages Statiques"
    folder: "content/pages"
    format: "json" # Stocke les métadonnées au format JSON
    create: false # Ne crée pas de nouvelles pages statiques via le CMS, gère juste les métadonnées existantes
    files:
      - file: "content/pages/contact.json"
        label: "Détails de la Page Contact"
        fields:
          - { label: "Titre de la Page", name: "pageTitle", widget: "string" }
          - { label: "Texte d'introduction", name: "introText", widget: "markdown" }
          # Vous pourriez ajouter d'autres champs pour les infos de contact, horaires, etc.
